//2nd Problem
//
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms would be:
1-2-3-5-8-13-21-34-55-89...
By considering the terms in the Fibonacci sequence whose values do not exceed four 
million, find the sum of the even-valued terms.
*/

public class Problem2 {
    public static void main(String args[]){
        int v = 2;//Sets at two because that is where the sum starts after you compute the first sum
        int nb1 = 1;
        int nb2 = 2;
        int na = 0;
        //4000000
        while (v < 4000000){
            na = nb1 + nb2;
            nb1 = nb2;
            nb2 = na;

            if (na%2 == 0){
                v += na;
            }
        }
        System.out.println(v);
    }
}
